name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    env:
      VERSION: 0.1.0
      NUGET_API_KEY: ${{secrets.NUGET_API_KEY}}

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore /property:Version=$VERSION-$GITHUB_RUN_NUMBER
    - name: Test
      run: dotnet test --no-restore --verbosity normal
    - name: Publish Nuget
      run: dotnet nuget push TeamsHook.NET/bin/Release/TeamsHook.NET.$VERSION-$GITHUB_RUN_NUMBER.nupkg -k $NUGET_API_KEY -s https://api.nuget.org/v3/index.json